#!/bin/bash

# Verifica se foi passado algum argumento
if [ $# -eq 0 ]; then
    echo "Usage: $0 [docker-compose options]"
    exit 1
fi

# Executa o docker-compose
docker compose "$@" -d

# Verifica se o docker-compose foi executado com sucesso
if [ $? -eq 0 ]; then
    # Reproduz o arquivo de áudio para indicar sucesso
    mpg123 -q /usr/local/bin/poze.mp3 &

    # Guarda o PID do mpg123
    mpg123_pid=$!

    # Exibe mensagem de sucesso
    echo -e "\n\x1b[32m ==================================\x1b[0m"
    echo -e "\x1b[32m||  Música tocando em background  ||\x1b[0m"
    echo -e "\x1b[32m ==================================\x1b[0m\n"
    echo -e "\x1b[33mPara parar a música, execute o comando:\x1b[0m"
    echo -e "\x1b[33m> sudo kill $mpg123_pid\x1b[0m"
    echo -e "\x1b[32m===================================\x1b[0m\n"
fi

# Fim do script